# on: [push, pull_request]

# jobs:
#   pact-create-tag:
#     runs-on: ubuntu-latest
#     env:
#       version: "1.0.0"
#       application_name: "usersInteractionsProvider"
#       PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
#       PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
#     steps:
#       - uses: pactflow/actions/create-version-tag@v1.0.1
#         env:
#           tag: ${{ github.sha }}

#   publish-pact-files:
#     runs-on: ubuntu-latest
#     env:
#       version: "1.0.0"
#       application_name: "usersInteractionsConsumer"
#       PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
#       PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pactflow/actions/publish-pact-files@v1.0.1
#         env:
#           pactfiles: users_frontend/tests/pacts


on: [push, pull_request]

jobs:
  publish-pact-files:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.sha }} # setting the git sha to version
      application_name: "usersInteractionsConsumer"
      PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Get the version number
        id: get_version
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
      - uses: pactflow/actions/publish-pact-files@v1.0.1
        env:
          pactfiles: users_frontend/tests/pacts
          CI: 'true' # setting CI to true
          MY_CI_COMMIT: ${{ github.sha }} # setting MY_CI_COMMIT to the git sha
          MY_GIT_SHA: ${{ github.sha }} # setting MY_GIT_SHA to the git sha
          MY_CI_BRANCH: ${{ github.ref }} # setting MY_CI_BRANCH to the git branch

  pact-create-tag:
    needs: publish-pact-files
    runs-on: ubuntu-latest
    env:
      version: ${{ github.sha }} # setting the git sha to version
      application_name: "usersInteractionsProvider"
      PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: pactflow/actions/create-version-tag@v1.0.1
        env:
          tag: prod-${{ github.sha }} # setting the tag to prod-git sha

